### ISSUE TITLE
Test fail with both project complete and step-by-step initial

### ISSUE THREAD

**Issue by flypig123456** [grails-guides/grails-custom-security-tenant-resolver#1]
First, thanks a lot for provide a multi-tenant guide with security. I'm looking for a solution in this field.
But I can't pass the test. I receive info like this:

Test HttpHeader resolver throws an exception outside a web request

Expected exception of type 'org.grails.datastore.mapping.multitenancy.exceptions.TenantNotFoundException', but got 'java.lang.NullPointerException'
	at org.spockframework.lang.SpecInternals.checkExceptionThrown(SpecInternals.java:85)
	at org.spockframework.lang.SpecInternals.thrownImpl(SpecInternals.java:72)
	at demo.CurrentUserByJwtTenantResolverSpec.Test HttpHeader resolver throws an exception outside a web request(CurrentUserByJwtTenantResolverSpec.groovy:24)
Caused by: java.lang.NullPointerException: Cannot invoke method resolveTenantIdentifier() on null object
	at demo.CurrentUserByJwtTenantResolverSpec.Test HttpHeader resolver throws an exception outside a web request(CurrentUserByJwtTenantResolverSpec.groovy:21)
Test HttpHeader value is the tenant id when a request is present

java.lang.NullPointerException: Cannot invoke method resolveTenantIdentifier() on null object
	at demo.CurrentUserByJwtTenantResolverSpec.Test HttpHeader value is the tenant id when a request is present(CurrentUserByJwtTenantResolverSpec.groovy:68)
Test not tenant id found

Expected exception of type 'org.grails.datastore.mapping.multitenancy.exceptions.TenantNotFoundException', but got 'java.lang.NullPointerException'
	at org.spockframework.lang.SpecInternals.checkExceptionThrown(SpecInternals.java:85)
	at org.spockframework.lang.SpecInternals.thrownImpl(SpecInternals.java:72)
	at demo.CurrentUserByJwtTenantResolverSpec.Test not tenant id found(CurrentUserByJwtTenantResolverSpec.groovy:38)
Caused by: java.lang.NullPointerException: Cannot invoke method resolveTenantIdentifier() on null object
	at demo.CurrentUserByJwtTenantResolverSpec.Test not tenant id found(CurrentUserByJwtTenantResolverSpec.groovy:35)

Plans for current logged user are retrieved

java.lang.IllegalStateException: No GORM implementations configured. Ensure GORM has been initialized correctly
	at org.grails.datastore.gorm.GormEnhancer.findSingleDatastore(GormEnhancer.groovy:380)
	at grails.gorm.multitenancy.Tenants.withId(Tenants.groovy:167)
	at demo.PlanControllerSpec.Plans for current logged user are retrieved(PlanControllerSpec.groovy:92)

**Comment by flypig123456** [comment]
After install two dependency in Build.gradle likes
    compile "org.grails.plugins:views-json:1.2.5"
    compile 'org.grails:grails-datastore-rest-client:5.0.0.RC2'
 I pass the test of CurrentUserByJwtTenantResolverSpec

But I still can't pass test PlanControllerSpec

**Comment by sdelamo** [comment]
Test pass for me and in Travis: 

https://travis-ci.org/grails-guides/grails-custom-security-tenant-resolver

Not sure how to help you.
